/**
 * Constantes compartidas de la aplicación
 */

export const TIPOS_PROCESO = [
  "ILA",
  "ESE LOCAL",
  "ESE FORANEO",
  "VISITA LOCAL",
  "VISITA FORANEA",
  "ILA CON BURÓ DE CRÉDITO",
  "ESE LOCAL CON BURÓ DE CRÉDITO",
  "ESE FORANEO CON BURÓ DE CRÉDITO",
  "ILA CON INVESTIGACIÓN LEGAL",
  "ESE LOCAL CON INVESTIGACIÓN LEGAL",
  "ESE FORANEO CON INVESTIGACIÓN LEGAL",
  "BURÓ DE CRÉDITO",
  "INVESTIGACIÓN LEGAL",
  "SEMANAS COTIZADAS",
] as const;

export type TipoProcesoType = typeof TIPOS_PROCESO[number];

export const CAUSALES_SALIDA = [
  "RENUNCIA VOLUNTARIA",
  "VIGENTE",
  "RECORTE DE PERSONAL",
  "TÉRMINO DE CONTRATO",
  "TERMINACIÓN DE PROYECTO",
  "TÉRMINO DE PERIODO DE PRUEBA",
  "REESTRUCTURACIÓN",
  "CAMBIO DE ADMINISTRACIÓN",
  "CIERRE DE EMPRESA",
  "POR ANTIGÜEDAD NO HAY INFORMACIÓN EN SISTEMA",
  "POR POLÍTICAS DE PRIVACIDAD NO DAN REFERENCIAS LABORALES",
  "BAJO DESEMPEÑO",
  "AUSENTISMO",
  "ABANDONO DE EMPLEO",
  "ACUMULACIÓN DE FALTAS INJUSTIFICADAS",
  "INCUMPLIMIENTO DE POLÍTICAS INTERNAS",
  "NO APEGO A POLÍTICAS Y PROCESOS",
  "CONDUCTA INADECUADA",
  "CONFLICTIVO",
  "VIOLACIÓN AL CODIGO DE CONDUCTA Y ÉTICA (DESHONESTIDAD)",
  "FALTA DE PROBIDAD",
  "PERDIDA DE CONFIANZA",
  "NO RENOVACIÓN DE CONTRATO",
  "BAJA CON CAUSAL",
  "BAJA ADMINISTRATIVA",
  "ABUSO DE CONFIANZA",
  "FALSIFICACIÓN DE DOCUMENTOS",
  "SUSTRACCIÓN DE COMBUSTIBLE",
  "ALCOHOLISMO",
  "PERDIDA DE RECURSOS / MATERIAL DE LA EMPRESA",
  "DAÑO A UNIDAD VEHICULAR",
] as const;

export type CausalSalidaType = typeof CAUSALES_SALIDA[number];

export const ESTATUS_INVESTIGACION = [
  "en_revision",
  "revisado",
  "terminado",
] as const;

export type EstatusInvestigacionType = typeof ESTATUS_INVESTIGACION[number];

export const ESTATUS_INVESTIGACION_LABELS: Record<EstatusInvestigacionType, string> = {
  en_revision: "En investigación",
  revisado: "Revisado",
  terminado: "Finalizado",
};

// Psicométricas — baterías disponibles (ajustar según proveedor)
export const BATERIAS_PSICOMETRICAS = [
  "BATERIA_BASICA",
  "BATERIA_ADMINISTRATIVA",
  "BATERIA_VENTAS",
  "BATERIA_OPERATIVA",
  "BATERIA_IT",
  "BATERIA_GERENCIAL",
  "BATERIA_FINANZAS",
  "BATERIA_RECURSOS_HUMANOS",
  "BATERIA_LOGISTICA",
  "BATERIA_SERVICIO_CLIENTE",
  "BATERIA_PRODUCCION",
  "BATERIA_SEGURIDAD",
  "BATERIA_CALIDAD",
  "BATERIA_LIDERAZGO",
  "BATERIA_CREDITO_COBRANZA",
  "BATERIA_PERSONALIZADA",
] as const;
export type BateriaPsicometricaType = typeof BATERIAS_PSICOMETRICAS[number];
